language: java
script:
  - mvn test -f ./nutritechAPI/pom.xml
  - cd ./nutritechAPI
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
jdk:
  - oraclejdk11
services:
  - docker
cache:
directories:
  - "$HOME/.cache"
