language: java
script:
  - mvn test -f ./nutritechAPI/pom.xml
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
jdk:
  - oraclejdk11
services:
  - docker
cache:
directories:
  - "$HOME/.cache"
deploy:
    provider: script
    script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
    skip_cleanup: true
    on:
    tags: true